export interface Product {
  id: string
  name: string
  price: number
  category: string
  description: string
  image: string
  imageAlt?: string
  color: string
  sold?: boolean
}

export const categories = [
  "Todo",
  "Iluminacion",
  "Ceramica",
  "Figuras",
] as const

export type Category = (typeof categories)[number]

export const products: Product[] = [
  {
    id: "flexo-azul",
    name: "Flexo Azul Cielo",
    price: 85,
    category: "Iluminacion",
    description: "Lampara de escritorio flexible en azul cielo con detalles cromados. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pLampara%20azul%20flexo-twd06uCsmLgf2MFNLR1YJ7AwtqMYnk.jpg",
    color: "#7BBBD4",
  },
  {
    id: "globo-rojo-tallado",
    name: "Globo Rojo Tallado",
    price: 120,
    category: "Iluminacion",
    description: "Base tallada en rojo coral con globo de cristal opalino y detalles en laton. Anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pLampara%20roja%20fondo70s-u0HSmpnhOwZ3vVfJ91NZZBwiIrHgac.jpg",
    color: "#E04A3E",
  },
  {
    id: "globo-rojo-cromado",
    name: "Globo Rojo Cromado",
    price: 95,
    category: "Iluminacion",
    description: "Cuerpo rojo con acabados cromados y globo de vidrio opalino. Space age anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pLamparita%20roja%20pan%CC%83uelo%20verde-I9GMaevKHwIhAjJSZUM1JoF6qkjzTa.jpg",
    color: "#E04A3E",
  },
  {
    id: "perfumero-verde",
    name: "Lampara Verde Opalina",
    price: 135,
    category: "Iluminacion",
    description: "Lampara en verde brillante con globo opalino. Forma de perfumero. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pPerfumero%20verde-iOleJCJSFq08ZRptSHx4YV35pmsk1v.jpg",
    color: "#4AAF5B",
  },
  {
    id: "lampara-seta-cromada",
    name: "Lampara Seta Cromada",
    price: 110,
    category: "Iluminacion",
    description: "Lampara seta con base cromada y globo opalino blanco. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A6160-bAW48hAwhIqUTeUUh0AmvolGAXIfgT.jpg",
    color: "#C0C0C0",
  },
  {
    id: "aceiteras-ambar",
    name: "Aceiteras Ambar 70s",
    price: 48,
    category: "Ceramica",
    description: "Juego de aceiteras en vidrio ambar soplado. Estilo mediterraneo anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pAceiteras%20ambar70s-mFxms2H0BCCAE0CfTnaSNwl89s2GhO.jpg",
    color: "#D4A574",
  },
  {
    id: "jarron-pajaro",
    name: "Jarron Pajaro Porcelana",
    price: 75,
    category: "Ceramica",
    description: "Jarron de porcelana blanca con pajaro pintado a mano. Pieza unica.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A9319-rm4dRx2kuK59pbyCVb9JG1GxR2KCWD.jpg",
    color: "#F8BBD9",
  },
  {
    id: "cafetera-porcelana",
    name: "Cafetera Porcelana",
    price: 65,
    category: "Ceramica",
    description: "Cafetera italiana con vaso de porcelana decorada. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pCafetera%20porcelana%20con%20vase-DWjEj0chQzJaIOFFuXmCsl5adrzoYH.jpg",
    color: "#8B4513",
  },
  {
    id: "cristaleria-ambar",
    name: "Cristaleria Ambar",
    price: 55,
    category: "Ceramica",
    description: "Set de copas y jarras en vidrio ambar. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pAmbar-iTlJyleGaP213gekwvTpP5KevSqWmm.jpg",
    color: "#D4A574",
  },
  {
    id: "botella-licor-naranja",
    name: "Botella Licor Naranja",
    price: 42,
    category: "Ceramica",
    description: "Botella de licor en vidrio naranja con tapon dorado. Anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pBotella%20licor%20naranja-jjFqb7eMIKEEEsL5ZETjZxOLRDYa3B.jpg",
    color: "#FF6B35",
  },
  {
    id: "platos-festoneados",
    name: "Platos Festoneados Oro",
    price: 38,
    category: "Ceramica",
    description: "Set de platos con borde festoneado y filete dorado. Anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A5643-QZMWpRBBbcB2QiDvwkBXslVJdvhlrh.jpg",
    color: "#D4AF37",
  },
  {
    id: "jarron-naranja",
    name: "Jarron Naranja Pop",
    price: 68,
    category: "Ceramica",
    description: "Jarron de vidrio opalino naranja. Estilo pop anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A5623-BWsCcWgPyhyPe1NEbyM0x8aaAQkGkf.jpg",
    color: "#FFA500",
  },
  {
    id: "decantador-ambar",
    name: "Decantador Ambar",
    price: 58,
    category: "Ceramica",
    description: "Decantador de vidrio ambar con tapon de madera. Artesanal.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A9314-sGWMFLCf75zvQwk7yvkAMf4k4IDKSd.jpg",
    color: "#8B4513",
  },
  {
    id: "decantador-negro",
    name: "Decantador Negro",
    price: 72,
    category: "Ceramica",
    description: "Decantador de ceramica negra esmaltada. Pieza unica anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A9864-EKfjapipAolSZRI3pS6FcfLDTzq8jS.jpg",
    color: "#2C2420",
  },
  {
    id: "cafetera-pyrex",
    name: "Cafetera Pyrex France",
    price: 45,
    category: "Ceramica",
    description: "Cafetera Pyrex con detalles dorados. Made in France anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pCafetera%20Pyrex%20France-gwvCayFukU0MgO70Ol7uPWFN1JpyGy.jpg",
    color: "#DAA520",
  },
  {
    id: "cafetera-valira",
    name: "Cafetera Valira",
    price: 35,
    category: "Ceramica",
    description: "Cafetera Valira porcelana blanca con lineas rojas. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pCafetera%20Valira-8wuPvPwD5nf8ikBpwsG5xuYjEAupLr.jpg",
    color: "#DC143C",
  },
  {
    id: "bambi-vintage",
    name: "Bambi Craquelado",
    price: 55,
    category: "Figuras",
    description: "Figura de Bambi con acabado craquelado y detalles dorados. Anos 50.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pBambi1-FDmA9UVowC2HrmHrqIWKuWqdYTTrtM.jpg",
    color: "#C9A961",
  },
  {
    id: "cafetera-cafe",
    name: "Cafetera Vintage Cafe",
    price: 38,
    category: "Ceramica",
    description: "Cafetera de cristal con letras 'Cafe'. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pCafetera%20Randwyck%20Maastricht-7PKIVhzSTEMyPPaW06Pr0LJ9w9aRsU.jpg",
    color: "#FF6347",
  },
  {
    id: "bolsos-baquelita",
    name: "Bolsos Baquelita",
    price: 85,
    category: "Figuras",
    description: "Par de bolsos de baquelita marron con cadena dorada. Anos 40.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A8436-lhllAtQvyJD25Zpm6ntsrAH7I6f6Tt.jpg",
    color: "#5D4037",
  },
  {
    id: "muebles-miniatura",
    name: "Muebles Miniatura",
    price: 42,
    category: "Figuras",
    description: "Set de muebles de jardin en plastico. Alemania anos 50.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pAlemania%20plastico%201950-jlhchbvZTQ1hNCc9GhRZbsRZTcqUZS.jpg",
    color: "#DC143C",
  },
  {
    id: "aceitera-soplado",
    name: "Aceitera Vidrio Soplado",
    price: 52,
    category: "Ceramica",
    description: "Aceitera de vidrio ambar soplado a mano. Artesanal.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pAceitera%20vidrio%20soplado-aszvOxhcPn0E5s5cqeFo1wiYybkrFk.jpg",
    color: "#D4A574",
  },
  {
    id: "agenda-genda",
    name: "Agenda Genda Vintage",
    price: 28,
    category: "Figuras",
    description: "Par de agendas Genda con acabado esmaltado. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A7963-8TyHo67Ewya2JvVeFi614ssp2MqVSi.jpg",
    color: "#DAA520",
  },
  {
    id: "jinete-vintage",
    name: "Jinete Vintage",
    price: 35,
    category: "Figuras",
    description: "Figura de jinete a caballo con sombrero rojo y traje amarillo. Coleccion anos 60.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A9125-8zSJgKzZA18GQVaiOb4zZoTwV0oFNu.jpg",
    color: "#2E7D32",
  },
  {
    id: "tetera-verde",
    name: "Tetera Verde Retro",
    price: 62,
    category: "Ceramica",
    description: "Tetera de ceramica verde oliva con patron geometrico. Anos 70.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/p001A6169-hAZt3QBIELsOzpwCFeH5KzKhMQhSW0.jpg",
    color: "#6B8E23",
  },
]
